modLoader="javafml"
loaderVersion="[31,)"
issueTrackerURL="http://www.github.com/MelanX/InventorySwitch/issues/"

[[mods]]
modId="invswitch"
version="${file.jarVersion}"
displayName="InventorySwitch"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/inventoryswitch.json"
displayURL="www.curseforge.com/members/melanx/"
#logoFile="examplemod.png"
credits=""
authors="MelanX"
description='''
A mod to change inventories for 2 players on a server.
'''

[[dependencies.invswitch]]
    modId="forge"
    mandatory=true
    versionRange="[31.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.invswitch]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15.2,)"
    ordering="NONE"
    side="BOTH"
